# Database Schema Yaml

# users
id: integer (primary key)
first_name: text
last_name: text

# courses
id: integer (primary key) (course_code)
title: text
description: text

# user_courses
user_id: integer (foreign key) (users.id)
course_id: integer (foreign key) (courses.id)
